version: '3'
services:
  accesspointmap-db:
    build: ./ms_accesspointmap_db
    volumes:
      - ./apm-db:/var/opt/mssql/data
    ports:
      - "1433:1433"
  accesspointmap-api:
    build: ./AccessPointMapWebApi/AccessPointMapWebApi
    ports:
      - "3201:80"
  server-cds:
    build: ./cds
    volumes: 
      - ./cds-files:/usr/src/app/images
    ports:
      - "3005:80"
volumes:
  apm-db:
  cds-files:
  