version: '3'
services:
  accesspointmap-db:
    build: ./ms_accesspointmap_db
    volumes:
      - ./apm-db:/var/opt/mssql/data
    ports:
      - "1401:1433"
  accesspointmap-api:
    build: ./AccessPointMapWebApi/AccessPointMapWebApi
    ports:
      - "3201:80"
    depends_on:
      - accesspointmap-db
  server-cds:
    build: ./cds
    volumes: 
      - ./cds-files-images:/usr/src/app/images
      - ./cds-files-projects:/usr/src/app/projects
    ports:
      - "3005:3005"
  personal-db:
    build: ./ms_personal_db
    volumes:
      - ./personal-db:/var/opt/mssql/data
    ports:
      - "1402:1433"
  personal-api:
    build: ./PersonalWebsiteWebApi/PersonalWebsiteWebApi
    ports:
      - "3004:80"
    depends_on: 
      - server-cds
      - personal-db
volumes:
  apm-db:
  personal-db:
  cds-files-images:
  cds-files-projects:
  